version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/home/user/app:z
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    command: iex -S mix phx.server
